### ISSUE TITLE
Api does not behave the same between former and current version

### ISSUE THREAD

**Issue by vesavlad** [opentransportro/transitime#14]
Hi,
best is the compare between your TC and our TC:

this doesn't give any data back - scheduleAdh
https://transitclock.xxx.xxx/api/v1/key/f78a2e9a/agency/26/reports/scheduleAdh?r=401&beginDate=02-14-2024&numDays=1&beginTime=00%3A01&endTime=23%3A59&allowableEarly=1&allowableLate=3

ours does:
https://xxx.net:8099/api/v1/key/f78a2e9a/agency/26/reports/scheduleAdh?r=401&beginDate=02-14-2024&numDays=1&beginTime=00%3A01&endTime=23%3A59&allowableEarly=1&allowableLate=3

and another one is avlReport
has no data: https://transitclock.xxx.xxx/api/v1/key/f78a2e9a/agency/26/reports/avlReport?v=4203&beginDate=02-14-2024&numDays=1&beginTime=12%3A55&endTime=13%3A20
has data: https://xxx.net:8099/api/v1/key/f78a2e9a/agency/26/reports/avlReport?v=4203&beginDate=02-14-2024&numDays=1&beginTime=12%3A55&endTime=13%3A20
For the avlReport , i noticed that dropdown with vehicles is empty in AVL reports in the web interface of your TC.

**Comment by vesavlad** [comment]
Reason for this is that that expected format was changed by mistake

Needed
![image](https://github.com/opentransportro/transitime/assets/1428537/42f1f30b-cab6-4698-b3ff-3518b91b23e7)

Actual:
![image](https://github.com/opentransportro/transitime/assets/1428537/f5eed8ee-35c4-4e24-a082-4ff346b51d3b)

**Comment by wkulesza** [comment]
Hey. Thanks @vesavlad 
I can confirm, after pulling in new image and up -d (without previously doing down), scheduleAdh report started working, but avlReport still returns empty data[]
BTW, TC seems to be very very inconsistent in data format... i guess we can either stick to what they use (US format) or base the date on the timezone chosen in docker-compose.yaml?
