### ISSUE TITLE
scheduled_time in new report tripsWithTravelTimes instead of old scheduledtime

### ISSUE THREAD

**Issue by wkulesza** [opentransportro/transitime#15]
Report tripsWithTravelTimes in it's response has now 'scheduled_time' value, while before it had 'scheduledtime'.
Can this be consistent - i.e. without '_' as all others ?
![obraz](https://github.com/opentransportro/transitime/assets/1014296/2c092760-5ec2-443b-901d-1ad913173735)

**Comment by vesavlad** [comment]
Fixing this ass follows: 
![image](https://github.com/opentransportro/transitime/assets/1428537/f6dd2b62-8d69-468e-958e-53c376f1c7b6)

**Comment by wkulesza** [comment]
Hi. Indeed naming has been corrected (scheduledtime instead of scheduled_time), but now, the endpoint returns duplicate stops with different vehicle (two same stop ids, with different times, different vehicle id). Also, what is different is the structure of difference_in_seconds.
used to be: "-00:06:48" - that indicates that vehicle was slate by 6mins 48 secs
now is (for the same stop id, but visible twice in response):
duplicate 1 - "13:29" (don't know the format)
duplicate 2 - "-00:06:48" - this is the same as normal.
