### ISSUE TITLE
API URLs don't include /api suffix ?

### ISSUE THREAD

**Issue by wkulesza** [opentransportro/transitime#18]
Original TC has /api as suffix to all api endpoints. This implementation doesn't use that. Same with /web suffix. Is it possible to configure TC in a way so that those prefixes are included (at least api part)?

**Comment by vesavlad** [comment]
Hi, currently the ```api``` is served and will be served under **/api/v1/** prefix. Web ```.jsp``` resources are served now **without** the **/web** prefix.

My plan is to transition the jsp's that have pure data outcome to an actual API and drop support for the current UI and replaced it something more modern. (see #13)
